### ISSUE TITLE
Multiple Dashboards Within A Dashboard

### ISSUE THREAD

**Issue by edolyne** [stijnelskens/sanity-plugin-plausible-analytics#1]
Using latest version of Sanity (3.31.0), when loading the dashboard the plugin is in a reload loop, continuously adding additional dashboards within the dashboard.

![CleanShot 2024-03-05 at 13 57 21@2x](https://github.com/stijnelskens/sanity-plugin-plausible-analytics/assets/3417857/dee67233-ddcf-4561-8544-05756ed826fa)

**Comment by stijnelskens** [comment]
Hi @edolyne 

Thanks for reaching out and using the plugin!
I tested it on the latest version: 
<img width="204" alt="image" src="https://github.com/stijnelskens/sanity-plugin-plausible-analytics/assets/12715277/f3c4a847-320b-4979-b591-d4a9c80017a6">

All works fine here..
Are you sure you have the right url in your sanity config?

**Comment by Jones-S** [comment]
I have the same problem. in my config I have this:

plausibleWidget({
   url: '<https://plausible.io/share/MYDOMAIN.com?auth=TOKEN>',
}),

I just created the share link so it should work.

I run `Sanity Studio version 3.28.0`

=== Edit:

I upgraded to `Sanity Studio version 3.48.1` but still I have the inception view

**Comment by Jones-S** [comment]
aaaah my bad: 
I had: 
```plausibleWidget({
url: '<https://plausible.io/share/MYDOMAIN.com?auth=TOKEN>',
}),
```
(`< and >` still in there)

Maybe @edolyne you have the same problem?

**Comment by edolyne** [comment]
@Jones-S Thanks, that was indeed the issue. I still had `< and >` still in it.

**Comment by stijnelskens** [comment]
Updated the readme!
